{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chartname }}
spec:
  selector:
    app: {{ .Values.chartname }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}
{{- end }}