- name: Ansible Playbook to Install and Setup grafana on Amazon Linux
  hosts: all
  tasks:
    - name: Download the grafana
      get_url:
        url: https://dl.grafana.com/oss/release/grafana-9.2.1.linux-amd64.tar.gz
        dest: /tmp/

    - name: Untar grafana
      unarchive:
        src: /tmp/grafana-9.2.1.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Start prometheus
      shell: |
        cd /tmp/grafana-9.2.1/bin
        nohup ./grafana-server > /tmp/null 2>&1 &
