- name: Ansible Playbook to Install and Setup Apache on amazon linux
  hosts: httpd
  tasks:
  - name: insatll apache server
    yum:
      name: httpd
      state: latest 
  - name: start the apcahe server
    service:
      name: httpd
      state: started
  - name: download url jquery template 
    unarchive:  
        src: https://www.free-css.com/assets/files/free-css-templates/download/page293/chocolux.zip
        dest: /var/www/html/
        remote_src: yes
  - name: restart the httpd server
    command: systemctl restart httpd 