kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "k8s-micro-frontend.fullname" . }}
  labels:
    {{- include "k8s-micro-frontend.labels" . | nindent 4 }}
data:
#   AWS_REGION: {{ .Values.region | default "us-east-1" }}
#   QUEUE_URL: {{ .Values.sqs_queue_url | default "https://sqs.us-east-1.amazonaws.com/315073111691/sqs-data-store" }}
    AWS_REGION: {{ .Values.region }}
    QUEUE_URL: {{.Values.sqs_queue_url }}