apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-micro-sqs-rds.fullname" . }}
  labels:
    {{- include "k8s-micro-sqs-rds.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.db_passwd }}