apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "kibana.fullname" . }}
  annotations:
   kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: k8sdemo.sainath.quest
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ template "kibana.fullname" . }}
            port:
              number: 80
