kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "k8s-micro-backend.fullname" . }}
  labels:
    {{- include "k8s-micro-backend.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.db_host }}
  DB_USER:  {{ .Values.db_user }}
  DB_NAME: {{ .Values.db_name }}
  DB_TABLE: {{ .Values.db_table  }}